(function (app) {
    'use strict';

    app.controller('studentProfileCtrl', studentProfileCtrl);

    studentProfileCtrl.$inject = ['$scope', 'apiService', 'notificationService'];

    function studentProfileCtrl($scope, apiService, notificationService) {
        $scope.pageClass = 'page-view-profile';

        $scope.markselect = {};

        $scope.data = [
            {
                "id": "0",
                "level": "High School",
                "grades": [
                    { "grade": "Grade 10" },
                    { "grade": "Grade 11" },
                    { "grade": "Grade 12" }
                ],
                "places": [
               {"place" : " ABBOTTS COLLEGE-CENTURION "},
{"place" : " ABBOTTS COLLEGE-NORTHCLIFF "},
{"place" : " ABBOTTS COLLEGE-PRETORIA EAST "},
{"place" : " ABDULLAH BIN SALAAM ISLAMIC CENTRE "},
    {"place" : " ABEL MOTSHOANE SECONDARY SCHOOL "},
    {"place" : " ACADEMIC QUALITY EDUCATION COLLEGE "},
    {"place" : " ACADEMY BUSINESS SCHOOL "},
    {"place" : " AFRICA HOUSE COLLEGE "},
    {"place" : " AFRICA INTERNATIONAL PRIVATE SCHOOL "},
    {"place" : " AFRICAN LEARDERSHIP ACADEMY "},
    {"place" : " AFRICAN SCHOOL FOR EXCELLENCE "},
    {"place" : " AFRIKAANSE HOËR SEUNSKOOL "},
    {"place" : " AFRIKAANSE HOËRSKOOL GERMISTON "},
    {"place" : " AFRO-KOMBS COLLEGE "},
    {"place" : " AHA-THUTO SECONDARY SCHOOL "},
    {"place" : " AHMED TIMOL SECONDARY SCHOOL "},
    {"place" : " ALAFANG SECONDARY SCHOOL "},
    {"place" : " AL-AQSA EXTENSION 10 SCHOOL "},
    {"place" : " AL-ASR EDUCATIONAL INSTITUTE SECONDARY SCHOOL "},
    {"place" : " AL-AZHAR INSTITUTE, JOHANNESBURG "},
    {"place" : " ALLANRIDGE SECONDARY SCHOOL "},
    {"place" : " ALLEN GLEN HIGH SCHOOL "},
    {"place" : " ALPHA TUTORIAL COLLEGE "},
    {"place" : " ALRAPARK SECONDARY SCHOOL "},
    {"place" : " ALTMONT TECHNICAL HIGH SCHOOL "},
    {"place" : " AMITY INTERNATIONAL "},
    {"place" : " AMOGELANG SECONDARY SCHOOL "},
    {"place" : " ANCHOR COMPREHENSIVE "},
    {"place" : " ANCHORAGE SECONDARY SCHOOL "},
    {"place" : " ARVANITES COLLEGE OF EDUCATION "},
    {"place" : " ASHBURY PREPARATORY SCHOOL "},
    {"place" : " ASHTON INTERNATIONAL COLLEGE "},
    {"place" : " ASSEMBLIES OF GOD COLLEGE "},
    {"place" : " ASSER MALOKA SECONDARY SCHOOL "},
    {"place" : " ATHLONE BOYS' HIGH SCHOOL "},
    {"place" : " ATLAS COMBINED SCHOOL "},
    {"place" : " AUCKLAND PARK ACADEMY OF EXCELLENCE "},
    {"place" : " AZAADVILLE MUSLIM SCHOOL "},
    {"place" : " AZARA SECONDARY SCHOOL "},
    {"place" : " B.B. MYATAZA SECONDARY SCHOOL "},
    {"place" : " BADIRILE SECONDARY SCHOOL "},
    {"place" : " BALMORAL COLLEGE "},
    {"place" : " BARACHEL CHRISTIAN ACADEMY "},
    {"place" : " BASA TUTORIAL INSTITUTE "},
    {"place" : " BEAULIEU COLLEGE "},
    {"place" : " BEDFORDVIEW HIGH SCHOOL "},
    {"place" : " BENONI CHRISTIAN SCHOOL "},
    {"place" : " BEYHAN COLLEGE "},
    {"place" : " BHUKULANI SECONDARY SCHOOL "},
    {"place" : " BLUE EAGLE HIGH SCHOOL "},
    {"place" : " BLUE HILLS COLLEGE "},
    {"place" : " BOITSHEPO SECONDARY SCHOOL "},
    {"place" : " BOITUMELO SECONDARY SCHOOL "},
    {"place" : " BOITUMELONG SECONDARY SCHOOL "},
    {"place" : " BOKGONI TECHNICAL SECONDARY SCHOOL "},
    {"place" : " BONA LESEDI SECONDARY SCHOOL "},
    {"place" : " BOPASENATLA SECONDARY SCHOOL "},
    {"place" : " BOPHELO-IMPILO PRIVATE "},
    {"place" : " BOSASA MOGALE LESEDING YOUTH DEVELOPMENT CENTRE "},
    {"place" : " BOSMONT MUSLIM SCHOOL "},
    {"place" : " BOTEBO-TSEBO SECONDARY SCHOOL "},
    {"place" : " BRACKEN HIGH SCHOOL "},
    {"place" : " BRAKPAN OPVOEDKUNDIGE SENTRUM "},
    {"place" : " BRANDCLIFF HOUSE "},
    {"place" : " BRESCIA HOUSE URSULINE CONVENT "},
    {"place" : " BRIGHT SPARK LEARNING ACADEMY "},
    {"place" : " CARPE DIEM ACADEMY "},
    {"place" : " CENTRAL SECONDARY SCHOOL "},
    {"place" : " CENTURION COLLEGE "},
    {"place" : " CHARTER INDEPENDENT COLLEGE "},
    {"place" : " CHURCHIL HIGH SCHOOL "},
    {"place" : " CORNERSTONE COLLEGE SEC. SCHOOL "},
    {"place" : " COVENANT COLLEGE "},
    {"place" : " CRAIGHALL COLLEGE "},
    {"place" : " CRAWFORD COLLEGE - SANDTON "},
    {"place" : " CRAWFORD PREPARATORY ITALIA "},
    {"place" : " CRAWFORD PREPARATORY PRETORIA "},
    {"place" : " CULTURA HIGH SCHOOL "},
    {"place" : " CURRO SERENGETI ACADEMY "},
    {"place" : " D.A. MOKOMA SECONDARY SCHOOL "},
    {"place" : " DAINFERN COLLEGE "},
    {"place" : " DALIWONGA SECONDARY SCHOOL "},
    {"place" : " DALPARK LEARNING ACADEMY "},
    {"place" : " DAMELIN COLLEGE HIGH SCHOOL - RANDBURG "},
    {"place" : " DASPOORT SECONDARY SCHOOL "},
    {"place" : " DAVID MAKHUBO SECONDARY SCHOOL "},
    {"place" : " DAWNVIEW HIGH SCHOOL "},
    {"place" : " DIEPSLOOT SECONDARY SCHOOL NO. 2 "},
    {"place" : " DIEPSLOOT WEST SECONDARY SCHOOL "},
    {"place" : " DILOPYE PRIMARY SCHOOL "},
    {"place" : " DINOTO TECHNICAL SECONDARY SCHOOL "},
    {"place" : " DIVERSITY HIGH SCHOOL "},
    {"place" : " DOMINICAN CONVENT SCHOOL (BELGRAVIA) "},
    {"place" : " DOXA DEO CHRISTIAN SCHOOL "},
    {"place" : " DR BW VILAKAZI SECONDARY SCHOOL "},
    {"place" : " DR WF NKOMO SECONDARY SCHOOL "},
    {"place" : " DR. A.T. MOREOSELE SECONDARY SCHOOL "},
    {"place" : " EBENEZER MARANATHA INSTITUTE "},
    {"place" : " EDEN COLLEGE "},
    {"place" : " EDENDALE PEPPS SCHOOL "},
    {"place" : " EDENICA PRIVATE SCHOOL "},
    {"place" : " EDEN-RIDGE HIGH SCHOOL "},
    {"place" : " EDUCATION INCORPORATED FOURWAYS "},
    {"place" : " ED-U-COLLEGE SECONDARY SCHOOL "},
    {"place" : " EDUMORE CHRISTRIAN ACADEMY "},
    {"place" : " EERSTERUST SECONDARY SCHOOL "},
    {"place" : " EKUKHANYISELWENI CHRISTIAN SCHOOL "},
    {"place" : " EL TABERNACLE CHRISTIAN COLLEGE "},
    {"place" : " EL ZERA PRIVATE SCHOOL "},
    {"place" : " ELDOMAINE SECONDARY SCHOOL "},
    {"place" : " ELITE COLLEGE "},
    {"place" : " EMDENI SECONDARY SCHOOL "},
    {"place" : " EMMANUEL PRIVATE SCHOOL "},
    {"place" : " EMPIRICAL TRAINING ACADEMY "},
    {"place" : " EMPRO ACADEMY "},
    {"place" : " ENTHEOS CHRISTIAN SCHOOL "},
    {"place" : " EPHES MAMKELI SECONDARY SCHOOL "},
    {"place" : " ESOKWAZI SECONDARY SCHOOL "},
    {"place" : " EXCELSIOR ROOIHUISKRAAL AKADEMIE "},
    {"place" : " FOCHVILLE  SECONDARY SCHOOL "},
    {"place" : " FOCHVILLE SECONDARY SCHOOL NO 2 "},
    {"place" : " FREEDOM PARK SECONDARY SCHOOL NO 1 "},
    {"place" : " FUMANA SECONDARY SCHOOL "},
    {"place" : " FUNDULWAZI SECONDARY SCHOOL "},
    {"place" : " GALEBOE MIDDLE SCHOOL "},
    {"place" : " GEKOMBINEERDE SKOOL CULLINAN "},
    {"place" : " GEKOMBINEERDE SKOOL NOORDERLIG "},
    {"place" : " GELUKSDAL SECONDARY SCHOOL "},
    {"place" : " GENERAL SMUTS HIGH SCHOOL "},
    {"place" : " GEREFORMEERDE GEKOMBINEERDE SKOOL DIRK POSTMA "},
    {"place" : " GERMISTON HIGH SCHOOL "},
    {"place" : " GLEN AUSTIN HIGH SCHOOL "},
    {"place" : " GLENBRACK HIGH SCHOOL "},
    {"place" : " GLOBAL COMBINED COLLEGE "},
    {"place" : " GRACE CHRISTIAN SCHOOL "},
    {"place" : " GREENSIDE HIGH SCHOOL "},
    {"place" : " HAMBANI COLLEGE "},
    {"place" : " HAMMANSKRAAL SECONDARY SCHOOL "},
    {"place" : " HANS KEKANA SECONDARY SCHOOL "},
    {"place" : " HATFIED TUITION AND SKILLS DEVELOPMENT CENTRE "},
    {"place" : " HATFIELD CHRISTIAN SCHOOL "},
    {"place" : " HB NYATHI SECONDARY SCHOOL "},
    {"place" : " HEARTWOOD INDEPENDENT SCHOOL "},
    {"place" : " HENLEY HIGH AND PREPARATORY SCHOOL "},
    {"place" : " HIMALAYA SECONDARY SCHOOL "},
    {"place" : " HLANGANANI SECONDARY SCHOOL "},
    {"place" : " HLOMPHANANG SECONDARY SCHOOL "},
    {"place" : " HOËR TEGNIESE SKOOL CAREL DE WET "},
    {"place" : " HOËR TEGNIESE SKOOL PRETORIA-TUINE "},
    {"place" : " HOËRSKOOL AKASIA "},
    {"place" : " HOËRSKOOL ALBERTON "},
    {"place" : " HOËRSKOOL BASTION "},
    {"place" : " HOËRSKOOL BIRCHLEIGH "},
    {"place" : " HOËRSKOOL CARLETONVILLE "},
    {"place" : " HOËRSKOOL CENTURION "},
    {"place" : " HOËRSKOOL DIE ANKER "},
    {"place" : " HOËRSKOOL DINAMIKA "},
    {"place" : " HOËRSKOOL DRIE RIVIERE "},
    {"place" : " HOËRSKOOL ELANDSPOORT "},
    {"place" : " HOËRSKOOL ELSBURG "},
    {"place" : " HOËRSKOOL ELSPARK "},
    {"place" : " HOËRSKOOL ERASMUS "},
    {"place" : " HOËRSKOOL FLORIDA "},
    {"place" : " HOËRSKOOL GARSFONTEIN "},
    {"place" : " HOËRSKOOL GOUDRIF "},
    {"place" : " HOËRSKOOL HANS MOORE "},
    {"place" : " HOËRSKOOL HERCULES "},
    {"place" : " HOËRSKOOL JAN VILJOEN "},
    {"place" : " HOËRSKOOL JEUGLAND "},
    {"place" : " HOËRSKOOL JOHAN JURGENS "},
    {"place" : " HOËRSKOOL JOHN VORSTER "},
    {"place" : " HOËRSKOOL KEMPTON PARK "},
    {"place" : " HOËRSKOOL MARAIS VILJOEN "},
    {"place" : " HOËRSKOOL MENLOPARK "},
    {"place" : " HOËRSKOOL MONTANA "},
    {"place" : " HOËRSKOOL OOS-MOOT "},
    {"place" : " HOËRSKOOL OOSTERLIG "},
    {"place" : " HOËRSKOOL OVERKRUIN "},
    {"place" : " HOËRSKOOL PRESIDENT "},
    {"place" : " HOËRSKOOL PRETORIA-NOORD "},
    {"place" : " HOËRSKOOL PRIMROSE "},
    {"place" : " HOËRSKOOL SILVERTON "},
    {"place" : " HOËRSKOOL STAATSPRESIDENT C R SWART "},
    {"place" : " HOËRSKOOL TRANSVALIA "},
    {"place" : " HOËRSKOOL TUINE "},
    {"place" : " HOËRSKOOL UITSIG "},
    {"place" : " HOËRSKOOL VANDERBIJLPARK "},
    {"place" : " HOËRSKOOL VORENTOE "},
    {"place" : " HOËRSKOOL WESTONARIA "},
    {"place" : " HOËRSKOOL WONDERBOOM "},
    {"place" : " HOËRSKOOL ZWARTKOP "},
    {"place" : " HOFMEYR SECONDARY SCHOOL "},
    {"place" : " HOLY ROSARY CONVENT SCHOOL "},
    {"place" : " HOLY TRINITY HIGH SCHOOL (CATHOLIC SEC.) "},
    {"place" : " HORIZON INTERNATIONAL HIGH SCHOOL "},
    {"place" : " HULWAZI SECONDARY SCHOOL "},
    {"place" : " I. R. LESOLANG SECONDARY SCHOOL "},
    {"place" : " IBHONGO SECONDARY SCHOOL "},
    {"place" : " INSTITUTE STATUS ACRES SECONDARY SCHOOL "},
    {"place" : " INTERNATIONAL PRE-UNIVERSITY COLLEGE "},
    {"place" : " ITHEMBA INSTITUTION OF TECHNOLOGY "},
    {"place" : " ITHEMBA STUDY CENTRE "},
    {"place" : " ITHUBA COMUNITY COLLEGE "},
    {"place" : " IZENZO KUNGEMAZWI COMMUNITY COLLEGE "},
    {"place" : " J.B. MATABANE SECONDARY SCHOOL "},
    {"place" : " JABULANI TECHNICAL SECONDARY SCHOOL "},
    {"place" : " JAFTA MAHLANGU SECONDARY SCHOOL "},
    {"place" : " JET NTEO SECONDARY SCHOOL "},
    {"place" : " JIYANA SECONDARY SCHOOL "},
    {"place" : " JOHANNESBURG SECONDARY SCHOOL "},
    {"place" : " JW SAINTS TECHNICAL COLLEGE "},
    {"place" : " KAGISO SECONDARY SCHOOL "},
    {"place" : " KELOKITSO COMPREHENSIVE SCHOOL "},
    {"place" : " KGETSE-YA-TSIE PRIMARY SCHOOL "},
    {"place" : " KGOKARE SECONDARY SCHOOL "},
    {"place" : " KGOMOTSO SECONDARY SCHOOL "},
    {"place" : " KHANYA-LESEDI SECONDARY SCHOOL "},
    {"place" : " KHUTLO-THARO SECONDARY SCHOOL "},
    {"place" : " KIBLER PARK SECONDARY SCHOOL "},
    {"place" : " KING DAVID SCHOOL-LINKSFIELD "},
    {"place" : " KINGSMEAD COLLEGE "},
    {"place" : " KINGSWAY SECONDARY SCHOOL "},
    {"place" : " KLIPSPRUIT-WES SECONDARY SCHOOL "},
    {"place" : " KRUGERSDORP HIGH SCHOOL "},
    {"place" : " KUBE SCHOOLS "},
    {"place" : " KWABHEKILANGA SECONDARY SCHOOL "},
    {"place" : " KWADEDANGENDLALE SECONDARY SCHOOL "},
    {"place" : " KWA-MAHLOBO SECONDARY SCHOOL "},
    {"place" : " L.G. HOLELE SECONDARY SCHOOL "},
    {"place" : " LA SALLE COLLEGE "},
    {"place" : " LAKESIDE SECONDARY SCHOOL "},
    {"place" : " LAVELA SECONDARY SCHOOL "},
    {"place" : " LAWLEY SECONDARY SCHOOL "},
    {"place" : " LEADERS CHRISTIAN ACADEMY "},
    {"place" : " LEAP SCIENCE AND MATHS SCHOOL "},
    {"place" : " LEARNING STRATEGIES INTERNATIONAL (LSI) COLLEGE "},
    {"place" : " LEBONE SECONDARY SCHOOL "},
    {"place" : " LEEDS BUSINESS SCHOOL "},
    {"place" : " LEHLABILE SECONDARY SCHOOL "},
    {"place" : " LEHWELERENG SECONDARY SCHOOL "},
    {"place" : " LENZ PUBLIC SCHOOL "},
    {"place" : " LETHAMAGA SECONDARY SCHOOL "},
    {"place" : " LIGNO VITAE ACADEMY "},
    {"place" : " LINGITJHUDU SECONDARY SCHOOL "},
    {"place" : " LIVERPOOL SECONDARY SCHOOL "},
    {"place" : " LOFENTSE GIRLS HIGH SCHOOL "},
    {"place" : " MABUYA SECONDARY SCHOOL "},
    {"place" : " MADIBANE COMPREHENSIVE SCHOOL "},
    {"place" : " MAHARENG SECONDARY SCHOOL "},
    {"place" : " MAHLASEDI HIGH SCHOOL "},
    {"place" : " MAHUBE VALLEY SECONDARY SCHOOL "},
    {"place" : " MAKHOSINI COMBINED SECONDARY SCHOOL "},
    {"place" : " MANDISA SHICEKA SECONDARY SCHOOL "},
    {"place" : " MAPENANE SECONDARY SCHOOL "},
    {"place" : " MAPETLA HIGH SCHOOL "},
    {"place" : " MAPHUTHA SECONDARY SCHOOL "},
    {"place" : " MARYVALE COLLEGE "},
    {"place" : " MASITHWALISANE SECONDARY SCHOOL "},
    {"place" : " MEYERTON SECONDARY SCHOOL "},
    {"place" : " MICHAEL MOUNT WALDORF SCHOOL "},
    {"place" : " MINERVA SECONDARY SCHOOL "},
    {"place" : " MODILATI SECONDARY SCHOOL "},
    {"place" : " MODIRI SECONDARY SCHOOL "},
    {"place" : " MODIRI TECHNICAL SCHOOL "},
    {"place" : " MOM SEBONE SECONDARY SCHOOL "},
    {"place" : " MONTESSORI ACADEMY AND COLLEGE "},
    {"place" : " MOQHAKA SECONDARY SCHOOL "},
    {"place" : " MOSES MAREN MISSION TECHNICAL SECONDARY SCHOOL "},
    {"place" : " MOSHATE SECONDARY SCHOOL "},
    {"place" : " MOSUPATSELA SECONDARY SCHOOL "},
    {"place" : " MPHETHI MAHLATSI SECONDARY SCHOOL "},
    {"place" : " MPONTSHENG SECONDARY SCHOOL "},
    {"place" : " NALEDI SECONDARY SCHOOL "},
    {"place" : " NASHVILLE CHRISTIAN COLLEGE "},
    {"place" : " NELLMAPIUS SECONDARY SCHOOL "},
    {"place" : " NEW EERSTERUST SECONDARY SCHOOL "},
    {"place" : " NEW MODEL PRIVATE COLLEGE "},
    {"place" : " NEWGATE COLLEGE "},
    {"place" : " NGHUNGHUNYANI COMPREHENSIVE "},
    {"place" : " NIMROD NDEBELE SECONDARY SCHOOL "},
    {"place" : " NKUMBULO SECONDARY SCHOOL "},
    {"place" : " NOORDWYK SECONDARY SCHOOL "},
    {"place" : " NORTHCLIFF HIGH SCHOOL "},
    {"place" : " NORTHWOOD INDEPENDENT HIGH SCHOOL "},
    {"place" : " NTIRISANO COMPREHENSIVE "},
    {"place" : " NUR-UL-ISLAM SCHOOL "},
    {"place" : " OAKDALE SECONDARY SCHOOL "},
    {"place" : " OOS-RAND AKADEMIE "},
    {"place" : " OOSRAND SECONDARY SCHOOL "},
    {"place" : " ORLANDO SECONDARY SCHOOL "},
    {"place" : " ORLANDO WEST SECONDARY SCHOOL "},
    {"place" : " OUR LADY OF WISDOM "},
    {"place" : " OXFORD TRAINING CENTRE "},
    {"place" : " PALMRIDGE EXT. 6 SECONDARY SCHOOL "},
    {"place" : " PARKLANDS HIGH SCHOOL "},
    {"place" : " PC TRAINING AND BUSINESS COLLEGE "},
    {"place" : " PC TRAINING AND BUSINESS COLLEGE "},
    {"place" : " PHAHAMA SECONDARY SCHOOL "},
    {"place" : " PHAKAMANI SECONDARY SCHOOL "},
    {"place" : " PHUMELELA PRIVATE COLLEGE "},
    {"place" : " PHUMULA GARDENS SECONDARY SCHOOL "},
    {"place" : " PHUTI JUNIOR SECONDARY SCHOOL "},
    {"place" : " PJ SIMELANE SECONDARY SCHOOL "},
    {"place" : " PONELOPELE ORACLE SECONDARY SCHOOL "},
    {"place" : " PRESTIGE COLLEGE "},
    {"place" : " PRESTIGIOUS AURETE SECONDARY SCHOOL "},
    {"place" : " PRETORIA CHINESE SCHOOL "},
    {"place" : " PRETORIA HIGH SCHOOL FOR GIRLS "},
    {"place" : " PRETORIA TECHNICAL HIGH SCHOOL "},
    {"place" : " PRIDE LEARNING ACADEMY "},
    {"place" : " PRINCESS HIGH SCHOOL "},
    {"place" : " PRINCESS PARK SECONDARY SCHOOL AND COLLEGE "},
    {"place" : " QEDILIZWE SECONDARY SCHOOL "},
    {"place" : " QOQA SECONDARY SCHOOL "},
    {"place" : " QUANTUM SECONDARY SCHOOL "},
    {"place" : " QUEENS HIGH SCHOOL "},
    {"place" : " QUEENS PRIVATE SCHOOL "},
    {"place" : " RADLEY COLLEGE "},
    {"place" : " RAKGOTSO SECONDARY SCHOOL "},
    {"place" : " RAMOLELLE COMBINED "},
    {"place" : " RAMOSUKULA PRIMARY SCHOOL "},
    {"place" : " RAND HILLS ACADEMY "},
    {"place" : " RAND MEISIESKOOL-GIRLS' SCHOOL "},
    {"place" : " RANDFONTEIN HIGH SCHOOL "},
    {"place" : " RANDFONTEIN SECONDARY SCHOOL "},
    {"place" : " RANTAILANE SECONDARY SCHOOL "},
    {"place" : " RATANDA SECONDARY SCHOOL "},
    {"place" : " REDDAM HOUSE PRIVATE SCHOOL "},
    {"place" : " REITUMETSE SECONDARY SCHOOL "},
    {"place" : " RELEBOGILE SECONDARY SCHOOL "},
    {"place" : " REPHAFOGILE SECONDARY SCHOOL "},
    {"place" : " RESHOGOFADITSWE SECONDARY SCHOOL "},
    {"place" : " RESIDENSIA SECONDARY SCHOOL "},
    {"place" : " REUTLWILE JUNIOR SECONDARY SCHOOL "},
    {"place" : " REVIVAL CHRISTIAN SCHOOL "},
    {"place" : " RHEMA CHRISTIAN SCHOOL "},
    {"place" : " RHODESFIELD TECHNICAL HIGH SCHOOL "},
    {"place" : " RIBANE-LAKA SECONDARY SCHOOL "},
    {"place" : " RIETVALLEI EXTENSION 1 SECONDARY SCHOOL "},
    {"place" : " RIVERLEA SECONDARY SCHOOL "},
    {"place" : " RIVERNORTH COMMERCIAL SCHOOL "},
    {"place" : " RIVERSIDE HIGH SCHOOL "},
    {"place" : " RIVONI SECONDARY SCHOOL "},
    {"place" : " ROBIN HOOD PRIVATE SECONDARY SCHOOL "},
    {"place" : " ROEDEAN SCHOOL (SA) "},
    {"place" : " RONDEBULT SECONDARY SCHOOL "},
    {"place" : " RONDEBULT SECONDARY SCHOOL NO. 2 "},
    {"place" : " ROOSEVELT HIGH SCHOOL "},
    {"place" : " ROSHNEE ISLAMIC SCHOOL "},
    {"place" : " ROSHNEE SECONDARY SCHOOL "},
    {"place" : " ROSTEC TECHNICAL COLLEGE "},
    {"place" : " ROSTEC TECHNICAL COLLEGE- PTA "},
    {"place" : " ROSTEC TECHNICAL COLLEGE-JHB "},
    {"place" : " ROYAL COLLEGE "},
    {"place" : " RUABOHLALE JUNIOR SECONDARY SCHOOL "},
    {"place" : " RUSOORD INTERMEDIATE SCHOOL "},
    {"place" : " RUST-TER-VAAL SECONDARY SCHOOL "},
    {"place" : " RUTASETJHABA SECONDARY SCHOOL "},
    {"place" : " S B S M PRIVATE SCHOOL "},
    {"place" : " SA COLLEGE SCHOOL "},
    {"place" : " SA INTERNATIONAL COLLEGE OF EDUCATION "},
    {"place" : " SACRED HEART COLLEGE "},
    {"place" : " SAGEWOOD SCHOOL "},
    {"place" : " SAHETI SCHOOL "},
    {"place" : " SAKHISIZWE SECONDARY SCHOOL "},
    {"place" : " SAMA INDEPENDENT PRIMARY AND SECONDARY SCHOOL "},
    {"place" : " SAMELSON COLLEGE "},
    {"place" : " SANDOWN HIGH SCHOOL "},
    {"place" : " SANDRINGHAM HIGH SCHOOL "},
    {"place" : " SANDTON TECHNICAL COLLEGE "},
    {"place" : " SANDTONVIEW COMBINED SCHOOL "},
    {"place" : " SAPPHIRE SECONDARY SCHOOL "},
    {"place" : " SAULRIDGE SECONDARY SCHOOL "},
    {"place" : " SCHAUMBURG COMBINED SCHOOL "},
    {"place" : " SCHOOL OF MERIT PRIVATE SCHOOL "},
    {"place" : " SCIENCES TUTORIALS "},
    {"place" : " SEAGENG SECONDARY SCHOOL "},
    {"place" : " SEANA MARENA SECONDARY SCHOOL "},
    {"place" : " SEBETSA-O-THOLEMOPUTSO "},
    {"place" : " SEDAVEN HIGH SCHOOL "},
    {"place" : " SEDCO COLLEGE "},
    {"place" : " SEDCO COLLEGE CARLETONVILLE "},
    {"place" : " SEDCO COLLEGE-PRETORIA "},
    {"place" : " SEEKERS PRIVATE HIGH SCHOOL "},
    {"place" : " SEHOPOTSO SECONDARY SCHOOL "},
    {"place" : " SEKANONTOANE SECONDARY SCHOOL "},
    {"place" : " SEKOLO SA BOROKGO SCHOOL "},
    {"place" : " SELELEKELA SECONDARY SCHOOL "},
    {"place" : " SENAOANE SECONDARY SCHOOL "},
    {"place" : " SENTHIBELE SENIOR SECONDARY SCHOOL "},
    {"place" : " SESHEGONG SECONDARY SCHOOL "},
    {"place" : " SETJHABA-SOHLE SECONDARY SCHOOL "},
    {"place" : " SETUMO - KHIBA SECONDARY SCHOOL "},
    {"place" : " SG MAFAESA SECONDARY SCHOOL "},
    {"place" : " SGODIPHOLA SECONDARY SCHOOL "},
    {"place" : " SHA-AREI TORAH PRIMARY SCHOOL "},
    {"place" : " SHANAN CHRISTIAN SCHOOL "},
    {"place" : " SHANGRI-LA ACADEMY SCHOOL "},
    {"place" : " SHEIKH ANTA DIOP COLLEGE "},
    {"place" : " SHEPPERD HIGH SCHOOL "},
    {"place" : " SIJABULILE SECONDARY SCHOOL "},
    {"place" : " SIKHULULEKILE SECONDARY SCHOOL "},
    {"place" : " SILVER OAKS SECONDARY SCHOOL "},
    {"place" : " SIMUNYE SECONDARY SCHOOL "},
    {"place" : " SIR ISAAC NEWTON HIGH SCHOOL "},
    {"place" : " SIR JOHN ADAMSON HIGH SCHOOL "},
    {"place" : " SIR PIERRE VAN RYNEVELD HIGH SCHOOL "},
    {"place" : " SITJHEJIWE SECONDARY SCHOOL "},
    {"place" : " SIYABONGA SECONDARY SCHOOL "},
    {"place" : " SIYABUSA SECONDARY SCHOOL "},
    {"place" : " SIYAPHAMBILI SECONDARY SCHOOL "},
    {"place" : " SIZANANI THUSANANG COMPREHENSIVE SCHOOL "},
    {"place" : " SIZWE SECONDARY SCHOOL "},
    {"place" : " SKYLINE HIGH SCHOOL "},
    {"place" : " SOLOMON MAHLANGU FREEDOM SCHOOL "},
    {"place" : " SONRISE CHRISTIAN SCHOOL "},
    {"place" : " SOSHANGUVE EAST SECONDARY SCHOOL "},
    {"place" : " SOSHANGUVE SECONDARY SCHOOL "},
    {"place" : " SOSHANGUVE TECHNICAL SECONDARY SCHOOL "},
    {"place" : " SPARROWS PRIVATE SCHOOL "},
    {"place" : " SPRINGS BOYS' HIGH SCHOOL "},
    {"place" : " SPRINGS SECONDARY SCHOOL "},
    {"place" : " ST ALBAN'S COLLEGE "},
    {"place" : " ST FRANCIS COLLEGE "},
    {"place" : " ST MARTIN DE PORRES HIGH SCHOOL "},
    {"place" : " ST MARY'S DIOCESAN SCHOOL FOR GIRLS "},
    {"place" : " ST PETER'S COLLEGE "},
        {"place" : " ST STITHIANS COLLEGE "},
    {"place" : " ST TERESA'S MERCY SENIOR PRIMARY AND HIGH SCHOOL "},
        {"place" : " STAR SCHOOLS "},
    {"place" : " SUMMAT INSTITUTE-PRETORIA CAMPUS "},
    {"place" : " SUMMERHILL COMBINED SCHOOL "},
    {"place" : " SUMMIT COLLEGE "},
    {"place" : " SUNCREST HIGH SCHOOL "},
    {"place" : " SUNWARD PARK HIGH SCHOOL "},
    {"place" : " TERSIA KING LEARING ACADEMY "},
    {"place" : " THAMSANQA SECONDARY SCHOOL "},
    {"place" : " THARABOLLO SECONDARY SCHOOL "},
    {"place" : " THE HILL HIGH SCHOOL "},
    {"place" : " THE KEEP LEARNING CENTRE "},
    {"place" : " THE KING'S SCHOOL (ROBIN HILLS) "},
    {"place" : " THE KING'S SCHOOL BRYANSTON "},
        {"place" : " THE SAMIT CHRISTIAN ACADEMY "},
    {"place" : " THE TRAINING ACADEMY "},
    {"place" : " THOLULWAZI SECONDARY SCHOOL "},
    {"place" : " THREE RIVERS CHRISTIAN ACDEMY "},
    {"place" : " THULANI SECONDARY SCHOOL "},
    {"place" : " THUTO BOHLALE SECONDARY SCHOOL "},
    {"place" : " THUTO KITSO SECONDARY SCHOOL "},
    {"place" : " THUTO LORE SECONDARY SCHOOL "},
    {"place" : " THUTO-KE-MAATLA COMPREHENSIVE SCHOOL "},
    {"place" : " THUTO-LESEDI SECONDARY SCHOOL "},
    {"place" : " THUTO-TIRO COMPREHENSIVE "},
    {"place" : " TIISETSONG SECONDARY SCHOOL "},
    {"place" : " TIYELELANI SECONDARY SCHOOL "},
    {"place" : " TOTUS TUUS INDEPENDENT SCHOOL "},
    {"place" : " TOWNVIEW HIGH SCHOOL "},
    {"place" : " TRINITY HOUSE HIGH SCHOOL "},
    {"place" : " TRINITY SECONDARY SCHOOL "},
    {"place" : " TSAKANE EXT.8 SECONDARY SCHOOL "},
    {"place" : " TSAKANE SECONDARY SCHOOL "},
    {"place" : " TSAKO THABO SECONDARY SCHOOL "},
    {"place" : " TSHEPO-THEMBA SECONDARY SCHOOL "},
    {"place" : " TSHWANE SECONDARY SCHOOL "},
    {"place" : " TSIBOGO PRIMARY SCHOOL "},
    {"place" : " TSOLO SECONDARY SCHOOL "},
    {"place" : " TSWASONGU SECONDARY SCHOOL "},
    {"place" : " TUKSSPORT HIGH SCHOOL "},
    {"place" : " TULIP COMBINED SCHOOL "},
    {"place" : " UNITED CHURCH PREPARATORY SCHOOL "},
    {"place" : " UNITED CITY COLLEGE "},
    {"place" : " VAAL ED U COLLEGE PRIVATE "},
    {"place" : " VEREENIGING GIMNASIUM "},
    {"place" : " VERITAS SECONDARY SCHOOL "},
    {"place" : " VINE COLLEGE "},
    {"place" : " VLAKFONTEIN SECONDARY SCHOOL "},
    {"place" : " VOSLOORUS COMPREHENSIVE SECONDARY SCHOOL "},
    {"place" : " VUKANI MAWETHU SECONDARY SCHOOL "},
    {"place" : " VUWANI SECONDARY SCHOOL "},
    {"place" : " WATERSHED PRIVATE SCHOOL "},
    {"place" : " WATERSRAND COMBINED SCHOOL "},
    {"place" : " WATERSRAND SECONDARY SCHOOL "},
    {"place" : " WAVELENGTH HIGH SCHOOL "},
    {"place" : " WEST RIDGE HIGH SCHOOL "},
    {"place" : " WHITE HOUSE COLLEGE "},
    {"place" : " WHITESTONE COLLEGE "},
    {"place" : " WIGGLES AND SQUIGGLES SCHOOL "},
    {"place" : " WILLOWMOORE HIGH SCHOOL "},
    {"place" : " WINDMILL PARK SECONDARY SCHOOL "},
    {"place" : " WISE-UP EDUCATION CENTRE "},
    {"place" : " ZAKARIYYA PARK SECONDARY SCHOOL "},

                ],
                "subjects": [
                      { "subject": "Afrikaans FAL" },
                    { "subject": "Afrikaans HL" },
                    { "subject": "Afrikaans SL" },
                      { "subject": "English FAL" },
                    { "subject": "English HL" },
                     { "subject": "IsiNdebele HL" },
                       { "subject": "IsiXhosa FAL" },
                      { "subject": "IsiXhosa HL" },
                         { "subject": "IsiZulu FAL" },
                      { "subject": "IsiZulu HL" },


                ]

            }, {
                "id": "1",
                "level": "University/College",
                "grades": [
                    { "grade": "First Year" },
                    { "grade": "Second Year" },
                    { "grade": "Third Year" },
                    { "grade": "Fourth Year" },
                    { "grade": "Year 5" },
                    { "grade": "Year 7" },
                    { "grade": "Honours" },
                    { "grade": "Masters" }
                ],
            }
        ];

    }

})(angular.module('BursifyApp'));

